# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: OTA4MDBjZTlhOGYxNzVmNDIxNDUzMDAwZWU4YjkxY2YyMTU0YTI5M2MzNDUxNmExY2FjMDNiNTM1NGMyZjRlOTFjZWMyNmI5NGY5MGJkMGZjMTljNjhiN2QxZTgxYThjMGFlZjlhNGQxYzVhYzZkNmQ2NDVjNjlkM2M2NDdlY2Q=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
